🚧 Update to SDK 33.0.0
🏭 This commit was automatically generated by generate-modules-sdk script.

Fix of this commit will be marked as:
🦻🏻👨🏿‍🔧😣🕵️

Full error log:
Error:  asset 2023-1-2--23-0-8--c3b93d9a-6d08-4073-902d-67973863f563/main.min.js 98.5 KiB [emitted] (name: main) 1 related asset
runtime modules 57 bytes 1 module
javascript modules 94.5 KiB
  ./src/moduleSampleBasic.tsx 2.93 KiB [built] [code generated] [2 errors]
  ./node_modules/@collboard/modules-sdk/dist/runtime/runtime.js 91.6 KiB [built] [code generated]
asset modules 84 bytes
  ./assets/hello-world-button.png 42 bytes [built] [code generated]
  ./assets/hello-world-icon.png 42 bytes [built] [code generated]
./package.json 705 bytes [built] [code generated]

ERROR in C:\Users\me\work\collboard\hello-world-module\src\moduleSampleBasic.tsx
./src/moduleSampleBasic.tsx 23:14-27
[tsl] ERROR in C:\Users\me\work\collboard\hello-world-module\src\moduleSampleBasic.tsx(23,15)
      TS2345: Argument of type '{ manifest: { name: string; version: string; description: string; contributors: string[]; license: string; repository: { type: string; url: string; }; title: { en: string; }; categories: string[]; icon: any; flags: { ...; }; }; place: UserInterfaceElementPlace.EdgeRight; createElement(systems: any): Promise<...>; }' is not assignable to parameter of type '{ manifest?: IModuleManifest | undefined; place: UserInterfaceElementPlace; order?: number | undefined; render(systems: ISystems): Promisable<...>; }'.
  Object literal may only specify known properties, and 'createElement' does not exist in type '{ manifest?: IModuleManifest | undefined; place: UserInterfaceElementPlace; order?: number | undefined; render(systems: ISystems): Promisable<...>; }'.

ERROR in C:\Users\me\work\collboard\hello-world-module\src\moduleSampleBasic.tsx
./src/moduleSampleBasic.tsx 23:28-35
[tsl] ERROR in C:\Users\me\work\collboard\hello-world-module\src\moduleSampleBasic.tsx(23,29)
      TS7006: Parameter 'systems' implicitly has an 'any' type.

webpack 5.35.1 compiled with 2 errors in 5767 ms

Error:
    at DevelopmentCompiler.<anonymous> (C:\Users\me\work\collboard\hello-world-module\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:91:37)
    at Generator.next (<anonymous>)
    at C:\Users\me\work\collboard\hello-world-module\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\me\work\collboard\hello-world-module\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:4:12)
    at Watching.handler (C:\Users\me\work\collboard\hello-world-module\node_modules\@collboard\modules-sdk\dist\colldev\services\Compiler\Compiler.js:85:72)
    at C:\Users\me\work\collboard\hello-world-module\node_modules\webpack\lib\Watching.js:204:9
    at Hook.eval [as callAsync] (eval at create (C:\Users\me\work\collboard\hello-world-module\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\me\work\collboard\hello-world-module\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at Watching._done (C:\Users\me\work\collboard\hello-world-module\node_modules\webpack\lib\Watching.js:201:28)